sudo: required
os:
    - linux
dist: trusty
addons:
    apt:
        packages:
            - libreoffice
            - libreoffice-dev
            - imagemagick
            - poppler-utils
language: node_js
node_js:
    - "10"
    - "12"
python:
    - "2.7"
before_script:
    - "npm run lint"
    - "sudo apt-get install ghostscript libreoffice"
    - "echo '/usr/bin/python' > env"
after_script:
    - npm run coveralls
git:
    depth: 10
cache:
    yarn: true
